version: 0.0.1-{build}

install:
  - nuget restore
  - cmd: C:\Windows\System32\regsvr32.exe /s "req\DebenuPDFLibrary64AX1013.dll"
  - cmd: C:\Windows\SysWOW64\regsvr32.exe /s "req\DebenuPDFLibraryAX1013.dll"
build:
  project: pdfsorter.net/pdfsorter.net.vbproj